# Generated by Django 5.2.7 on 2025-10-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
