# Generated by Django 5.2.7 on 2025-10-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workout_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms')], default='Chest', max_length=50),
        ),
    ]
