# Generated by Django 5.2.7 on 2025-10-15 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workout_muscle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
